app:
  client:
    tender-pro-url: "https://www.tender.pro/api"
    tender-tatneft: "https://tender.tatneft.ru"
    tender-ice-trade: "https://icetrade.by"

spring:
  application:
    name: Zavod_IT
  jackson:
    time-zone: UTC
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    show-sql: true

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
